apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: evaluation
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ template "evaluation.fullname" . }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "evaluation.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "evaluation.serviceAccountName" . }}
      containers:
      - name: evaluation
        image: "{{ .Values.image.evaluation.repository }}:{{ .Values.image.evaluation.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
{{ toYaml .Values.env | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - name: applicationui
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 10
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{- else }}{{ template "evaluation.fullname" . }}-config{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
