apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "evaluation.fullname" . }}-tls-secret"
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ template "evaluation.fullname" . }}
type: Opaque
